# docker compose for development

services:
  # FIXME: write frontend here
  backend: 
    restart: on-failure
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on: 
      - postgres
    environment:
      - CORS_ORIGIN=http://localhost:5173
      - DSN=host=postgres user=user database=database password=password port=5432
      - HALT_AFTER_SUCCESS # inherit
  postgres:
    image: postgres:alpine
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
