# docker compose for development

services:
  frontend: 
    restart: always
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
  backend: 
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
      # postgres:
      #   condition: service_healthy
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173} # inherit, default to http://localhost:5173
      - DSN=host=postgres user=user database=database password=password port=5432
      - HALT_AFTER_SUCCESS # inherit
      - CREDENTIALS_SOURCE # inherit
      - IN_MEMORY_DB # inherit
  # not necessary anymore. leaving it here in case you need it in the future
  # postgres:
  #   image: postgres:alpine
  #   hostname: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=user
  #     - POSTGRES_DB=database
  #   healthcheck:
  #     test: "pg_isready -U user -d database"
  #     interval: 5s
  #     retries: 3
