# TODO!
services:
  backend:
    restart: always
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ECHO_SERVES_FRONTEND_TOO=true
      - DSN # inherit
    # FIXME: mount (or whatever it's called) frontend dist into somewhere arount here (backend/static?) 
    # s.t. backend can see it. it currently doesn't work.
  frontend:
    # FIXME: just build and halt
