services:
  full:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - ECHO_SERVES_FRONTEND_TOO=true
      - DSN # inherit
