# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test, Check, and Format

on:
  push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        check-latest: true
        cache-dependency-path: |
          backend/go.sum
          go-tools/go.sum

    - name: Install staticcheck
      working-directory: ./backend/
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run tests
      working-directory: ./backend/
      run: |
        go vet ./...
        go fmt ./...
        go run honnef.co/go/tools/cmd/staticcheck@latest ./...
        go test -v ./...
        go build -n
        # src of the code below: https://developers.wano.co.jp/1883/
        git diff --exit-code --quiet
        if [ $? -eq 0 ]; then echo "ok"; else echo "git diff error"; exit 1; 
