# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test, Check, and Format

on:
  push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        check-latest: true
        cache-dependency-path: |
          backend/go.sum
          go-tools/go.sum

    - name: Install staticcheck
      working-directory: ./backend/
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run tests
      working-directory: ./backend/
      run: "
        # src of the code below: https://developers.wano.co.jp/1883/ (modified)
        function assert_no_change () { git diff --exit-code --quiet; if [ $? -eq 0 ]; then echo Go tests: $1 passed; else echo Go tests: $1 failed; exit 1; fi }
        
        echo Starting go vet...
        go vet ./...
        assert_no_change vet
        
        echo Starting go fmt...
        go fmt ./...
        assert_no_change fmt
        
        echo Starting staticcheck...
        go run honnef.co/go/tools/cmd/staticcheck@latest ./...
        assert_no_change staticcheck
        
        echo Starting go test...
        go test -v ./...
        assert_no_change test
        
        echo Starting go build...
        go build -n 2&>/dev/null
      "
